let
    url = "http://127.0.0.1:8000/predict/",
    body = "{
                ""cefoxSR1601000701"": {
                                            "" BMI"": 28.5,
                                            "" Body Age"": 80,
                                            ""Age"": 77.0,
                                            ""Gender"": ""Female"",
                                            ""Height"": 156.0,
                                            ""Body weight"": 60.0,
                                            ""Drinking"": ""yes"",
                                            "" Sleep Hour"": 0.0,
                                            ""Antihypertensive"": ""None"",
                                            ""Osteoporosis drug"": ""None"",
                                            ""Antidiabetic drug"": ""None"",
                                            "" Body Fat Percentage"": 41.4,
                                            "" Basal Metabolism"": 1363.7667,
                                            ""Total cholesterol"": 212.0,
                                            ""LDL cholesterol"": 123.0,
                                            ""HDL cholesterol"": 73.0,
                                            ""HbA1c"": 5.5,
                                            ""AST"": 22.0,
                                            ""ALT"": 30.0,
                                            ""LDH"": 159.0,
                                            ""Na"": 143.0,
                                            ""K"": 4.5,
                                            ""Diabetes mellitus"": ""Nothing"",
                                            "" Systolic Pressure"": 122.0,
                                            "" Diastolic Pressure"": 71.0,
                                            "" Mean Arterial Pressure"": 96.0,
                                            "" Pulse Rate"": 63.0,
                                            "" Irregular Pulse Flag"": "" false"",
                                            ""Blood sugar"": 88.0,
                                            ""Appetite Questionnaire results"": "" a lot"",
                                            ""Preference Questionnaire results"": ""I like light taste"",
                                            ""Sleep Questionnaire results"": ""Sleeping "",
                                            ""Anxiety about health Questionnaire results"": ""some"",
                                            ""I can go up and down stairs without being transmitted to the railing or wall"": ""yes"",
                                            ""I can walk for more than 15 minutes"": ""yes"",
                                            ""I am actively going out"": ""yes"",
                                            ""Do the cleaning and washing yourself"": ""yes"",
                                            ""Shop for daily necessities yourself"": ""yes"",
                                            ""Exercise function"": ""good"",
                                            ""Nutrition"": ""Observation required""
                                        },
                ""cefoxSR16010003701"": {
                                            "" BMI"": 28.5,
                                            "" Body Age"": 80,
                                            ""Age"": 77.0,
                                            ""Gender"": ""Female"",
                                            ""Height"": 156.0,
                                            ""Body weight"": 60.0,
                                            ""Drinking"": ""yes"",
                                            "" Sleep Hour"": 0.0,
                                            ""Antihypertensive"": ""None"",
                                            ""Osteoporosis drug"": ""None"",
                                            ""Antidiabetic drug"": ""None"",
                                            "" Body Fat Percentage"": 41.4,
                                            "" Basal Metabolism"": 1363.7667,
                                            ""Total cholesterol"": 212.0,
                                            ""LDL cholesterol"": 123.0,
                                            ""HDL cholesterol"": 73.0,
                                            ""HbA1c"": 5.5,
                                            ""AST"": 22.0,
                                            ""ALT"": 30.0,
                                            ""LDH"": 159.0,
                                            ""Na"": 143.0,
                                            ""K"": 4.5,
                                            ""Diabetes mellitus"": ""Nothing"",
                                            "" Systolic Pressure"": 122.0,
                                            "" Diastolic Pressure"": 71.0,
                                            "" Mean Arterial Pressure"": 96.0,
                                            "" Pulse Rate"": 63.0,
                                            "" Irregular Pulse Flag"": "" false"",
                                            ""Blood sugar"": 88.0,
                                            ""Appetite Questionnaire results"": "" a lot"",
                                            ""Preference Questionnaire results"": ""I like light taste"",
                                            ""Sleep Questionnaire results"": ""Sleeping "",
                                            ""Anxiety about health Questionnaire results"": ""some"",
                                            ""I can go up and down stairs without being transmitted to the railing or wall"": ""yes"",
                                            ""I can walk for more than 15 minutes"": ""yes"",
                                            ""I am actively going out"": ""yes"",
                                            ""Do the cleaning and washing yourself"": ""yes"",
                                            ""Shop for daily necessities yourself"": ""yes"",
                                            ""Exercise function"": ""good"",
                                            ""Nutrition"": ""Observation required""
                                        },
                ""cefoxSR1601004301"": {
                                            "" BMI"": 28.5,
                                            "" Body Age"": 80,
                                            ""Age"": 77.0,
                                            ""Gender"": ""Female"",
                                            ""Height"": 156.0,
                                            ""Body weight"": 60.0,
                                            ""Drinking"": ""yes"",
                                            "" Sleep Hour"": 0.0,
                                            ""Antihypertensive"": ""None"",
                                            ""Osteoporosis drug"": ""None"",
                                            ""Antidiabetic drug"": ""None"",
                                            "" Body Fat Percentage"": 41.4,
                                            "" Basal Metabolism"": 1363.7667,
                                            ""Total cholesterol"": 212.0,
                                            ""LDL cholesterol"": 123.0,
                                            ""HDL cholesterol"": 73.0,
                                            ""HbA1c"": 5.5,
                                            ""AST"": 22.0,
                                            ""ALT"": 30.0,
                                            ""LDH"": 159.0,
                                            ""Na"": 143.0,
                                            ""K"": 4.5,
                                            ""Diabetes mellitus"": ""Nothing"",
                                            "" Systolic Pressure"": 122.0,
                                            "" Diastolic Pressure"": 71.0,
                                            "" Mean Arterial Pressure"": 96.0,
                                            "" Pulse Rate"": 63.0,
                                            "" Irregular Pulse Flag"": "" false"",
                                            ""Blood sugar"": 88.0,
                                            ""Appetite Questionnaire results"": "" a lot"",
                                            ""Preference Questionnaire results"": ""I like light taste"",
                                            ""Sleep Questionnaire results"": ""Sleeping "",
                                            ""Anxiety about health Questionnaire results"": ""some"",
                                            ""I can go up and down stairs without being transmitted to the railing or wall"": ""yes"",
                                            ""I can walk for more than 15 minutes"": ""yes"",
                                            ""I am actively going out"": ""yes"",
                                            ""Do the cleaning and washing yourself"": ""yes"",
                                            ""Shop for daily necessities yourself"": ""yes"",
                                            ""Exercise function"": ""good"",
                                            ""Nutrition"": ""Observation required""
                                        }
            }",
    Source = Json.Document(Web.Contents(url,
                                    [Headers = [#"Content-Type"="application/json"],
                                            Content = Text.ToBinary(body) 
                                    ]   
                                )
                            ),
    #"Converted to Table" = Record.ToTable(Source),
    #"Extracted Values" = Table.TransformColumns(#"Converted to Table", {"Value", each Text.Combine(List.Transform(_, Text.From)), type text}),
    #"Renamed Columns" = Table.RenameColumns(#"Extracted Values",{{"Name", "SubjectID"}, {"Value", "Risk"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Risk", Percentage.Type}})
in
    #"Changed Type"