sa_01_header = ['No','SubjectID', 'Housing complex', 'Gender', 'Birthday', 'Age', 
                'certification of care need', 'Number of residents', 'Height', 
                'Body weight', 'Stride（cm)', 'Medical history', 'Disease name',
                'Regular hospital consultation', 'Antihypertensive', 
                'Antidepressant', 'Osteoporosis drug', 'Antidiabetic drug',
                'Other1', 'Smoking', 'Drinking', 
                'Family composition of living together', 
                'Care need certification time', 'Hobby・preference・habit', 
                'Activities', 'Community', 'Everyday', 
                'Everyday With or without blood pressure measurement', 
                'Whether or not to use a pedometer on a daily basis', 
                'Other2', 'right Measured value', 'right Evaluation', 
                'right Presence or absence of abnormality', 'left easured value',
                'left Evaluation', 'left Presence or absence of abnormality',
                'Locomotive Measured value', 
                'Locomotive Presence or absence of abnormality']

li_02_header = ['No','SubjectID', 'Date confirmed', 'Appetite Questionnaire results',
                'Eating habit Questionnaire results', 'Preference Questionnaire results', 
                'Sleep Questionnaire results','Anxiety about health Questionnaire results', 
                'Anxiety about forgetfulness Questionnaire results', 
                'I can go up and down stairs without being transmitted to the railing or wall', 
                'I can get up from the chair', 'I can walk for more than 15 minutes', 
                'I can walk without a cane', 'I am actively going out', 
                'Walking function Score', 'Walking function Evaluation', 
                'Do the cleaning and washing yourself', 'Shop for daily necessities yourself',
                'I can prepare your own meals', 
                'I can write the documents to be submitted to the government office by myself', 
                '自分で電話帳を調べ、電話をかけることができる', '生活機能 Score', 
                '生活機能 Evaluation', 'I have a counselor in case of trouble',         
                "I have a counselor when I'm sick", 
                "I have someone who will take me to the hospital when I'm sick", 
                'There are people who take care of me when I fall asleep', 
                'Relying on someone', 'ソーシャルサポート Score',  
                'ソーシャルサポート Evaluation', 
                'No weight loss of more than 2-3 kg in the last 6 months', 
                'No weight gain of more than 2-3 kg in the last 2 months', 
                'I can eat hard food',"When I drink tea or soup, I don't get sick", 
                "I don't mind thirst",
                '口腔・栄養 Score', 
                '口腔・栄養 Evaluation']

ir_04_header = ['No', 'SubjectID', 'Presence or absence of inspection record', 
                'Inspection date', 'Total cholesterol', 'LDL cholesterol', 
                'HDL cholesterol', 'Urea nitrogen', 'Creatinine',
                'Uric acid', 'Urine protein', 'Blood sugar', 'Diabetes diagnosis age',
                'HbA1c', 'AST', 'ALT', 'LDH', 'Retinopathy', 
                'Hypertension diagnosis age sodium', 'Na', 'K', 'ECG abnormalities',
                'Triglyceride', 'Diagnosis age of dyslipidemia', 
                'History of coronary artery disease', 'Chronic kidney disease diagnosis age',
                'Total protein', 'Albumin', 'Hematuria']

ev_05_header = ['No','SubjectID', 'Health status', 'Biological function', 
                'Exercise function', 'Nutrition', 'Cognitive function', 'Fall', 
                'High blood pressure', 'Arrhythmia', 'Osteoporosis', 
                'Diabetes mellitus', 'Exercise guidance', 'Nutrition guidance',
                'Life guidance']